Repository SSAFY-GoldMen/backend, pull requests merged in 2023-11, with the labels that each got.

#6 [Common] `ClientResponse` 타입 클래스 개발
  goldmen-common/src/main/java/com/goldmen/home/.gitkeep
  goldmen-common/src/main/java/com/goldmen/home/type/ClientResponse.java
Labels: ✨ feature

#9 [Client] 서울공공데이터 집 FetchAPI
  .gitignore
  goldmen-application/goldmen-batch/build.gradle
  goldmen-application/goldmen-batch/src/test/java/com/goldmen/home/BatchApplicationTest.java
  goldmen-client/seoul-client/src/main/java/com/goldmen/home/house/dto/SeoulOpenDataHouseAPIRequest.java
  goldmen-client/seoul-client/src/main/java/com/goldmen/home/house/service/SeoulOpenDataRentHouseClient.java
  goldmen-client/seoul-client/src/main/java/com/goldmen/home/house/vo/SeoulOpenDataHouse.java
  goldmen-client/seoul-client/src/main/java/com/goldmen/home/house/vo/SeoulOpenDataHouseData.java
  goldmen-client/seoul-client/src/main/java/com/goldmen/home/house/vo/SeoulOpenDataHouseWrapper.java
  goldmen-client/seoul-client/src/main/resources/application.yml
  goldmen-client/seoul-client/src/test/java/com/goldmen/home/SeoulClientTestConfiguration.java
  goldmen-client/seoul-client/src/test/java/com/goldmen/home/house/service/SeoulOpenDataSeoulOpenDataHouseHouseClientTest.java
  goldmen-client/seoul-client/src/test/resources/application.yml
Labels: ✨ feature, 🙏 P1

#10 [Applicatoin] 지하철 정보 모듈 개발
  goldmen-application/goldmen-api/src/main/resources/stationInformation.json
  goldmen-application/goldmen-batch/src/main/java/com/goldmen/home/BatchApplication.java
  goldmen-application/goldmen-batch/src/main/java/com/goldmen/home/station/service/StationService.java
  goldmen-application/goldmen-batch/src/main/java/com/goldmen/home/station/stationInformation.json
  goldmen-application/goldmen-batch/src/main/java/com/goldmen/home/station/vo/StationInfo.java
  goldmen-application/goldmen-batch/src/main/java/com/goldmen/home/station/vo/StationInfoRaw.java
  goldmen-application/goldmen-batch/src/test/java/com/goldmen/home/station/service/StationServiceTest.java
  goldmen-application/goldmen-batch/src/test/resources/stationInformation.json
  goldmen-client/seoul-client/src/main/java/com/goldmen/home/SeoulClientApplication.java
  goldmen-common/src/main/java/com/goldmen/home/.gitkeep
Labels: ✨ feature

#13 [Common] ApiResponse Type 을 설계 및 구현
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/controller/MemberController.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/service/MemberService.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/message/MemberMessage.java
  goldmen-common/src/main/java/com/goldmen/home/.gitkeep
  goldmen-common/src/main/java/com/goldmen/home/type/ApiResponse.java
  goldmen-common/src/main/java/com/goldmen/home/type/Message.java
Labels: ✨ feature

#18 [Application & Domain] 로그인 기능을 구현
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/controller/MemberController.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/dto/request/MemberLoginRequest.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/dto/request/MemberSignupRequest.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/mapper/MemberMapper.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/service/MemberService.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/message/MemberMessage.java
  goldmen-application/goldmen-api/src/test/java/com/goldmen/home/user/member/fixture/MemberFixture.java
  goldmen-application/goldmen-api/src/test/java/com/goldmen/home/user/member/service/MemberServiceTest.java
  goldmen-common/src/main/java/com/goldmen/home/type/ApiResponse.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/user/member/domain/MemberRepository.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/user/member/service/MemberLoadService.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/user/member/service/MemberServiceImpl.java
  goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/user/member/domain/MemberRepositoryTest.java
  goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/user/member/fixture/MemberFixture.java
  goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/user/member/service/MemberServiceImplTest.java
Labels: ✨ feature, ✅ test

#20 Fix(#19):KakaoAPIRequest 역할 추가
  goldmen-client/kakao-client/src/main/java/com/goldmen/home/dto/request/KakaoAPIRequest.java
  goldmen-client/kakao-client/src/main/java/com/goldmen/home/service/KakaoMapService.java
  goldmen-client/kakao-client/src/test/java/com/goldmen/home/service/KakaoMapServiceTest.java
Labels: 🚑 fix

#22 [Application] WebConfig 작성
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/global/WebConfig.java
Labels: ✨ feature, 🔧 config

#24 Feature/#23
  goldmen-application/goldmen-batch/src/main/java/com/goldmen/home/station/stationInformation.json
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/map/district/domain/District.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/map/district/domain/DistrictRepository.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/map/district/service/DistrictService.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/map/legal/domain/Legal.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/map/legal/domain/LegalRepository.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/map/legal/service/LegalService.java
  goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/map/district/domain/DistrictRepositoryTest.java
  goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/map/district/service/DistrictServiceTest.java
  goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/map/legal/domain/LegalRepositoryTest.java
  goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/map/legal/service/LegalServiceTest.java
Labels: ✨ feature

#26 [Client] 지하철 정보 저장 기능 구현
  goldmen-application/goldmen-api/src/test/java/com/goldmen/home/user/member/controller/MemberControllerTest.java
  goldmen-application/goldmen-batch/build.gradle
  goldmen-application/goldmen-batch/src/main/java/com/goldmen/home/station/service/StationService.java
  goldmen-application/goldmen-batch/src/main/resources/application.yml
  goldmen-application/goldmen-batch/src/test/java/com/goldmen/home/station/service/StationServiceTest.java
  goldmen-client/kakao-client/src/main/java/com/goldmen/home/config/property/KakaoAddressProperties.java
  goldmen-client/kakao-client/src/main/java/com/goldmen/home/dto/request/KaKaoKeywordAPIRequest.java
  goldmen-client/kakao-client/src/main/java/com/goldmen/home/dto/request/KakaoAddressAPIRequest.java
  goldmen-client/kakao-client/src/main/java/com/goldmen/home/service/KakaoMapService.java
  goldmen-client/kakao-client/src/main/java/com/goldmen/home/vo/Position.java
  goldmen-client/kakao-client/src/test/java/com/goldmen/home/service/KakaoMapServiceTest.java
  goldmen-client/seoul-client/src/main/java/com/goldmen/home/station/config/property/StationProperties.java
  goldmen-client/seoul-client/src/main/java/com/goldmen/home/station/service/SeoulOpenDataStationClient.java
  goldmen-client/seoul-client/src/main/java/com/goldmen/home/station/vo/StationInfo.java
  goldmen-client/seoul-client/src/main/java/com/goldmen/home/station/vo/StationInfoRaw.java
  goldmen-client/seoul-client/src/main/resources/application.yml
  goldmen-client/seoul-client/src/main/resources/stationInformation.json
  goldmen-client/seoul-client/src/test/java/com/goldmen/home/station/service/SeoulOpenDataStationClientTest.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/map/district/domain/District.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/map/legal/domain/Legal.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/metro/line/domain/LineRepository.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/metro/line/service/LineLoadService.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/metro/line/service/LineModifyService.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/metro/line/service/LineServiceImpl.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/metro/station/domain/StationRepository.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/metro/station/service/StationModifyService.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/metro/station/service/StationServiceImpl.java
  goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/metro/line/service/LineServiceImplTest.java
  goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/metro/station/service/StationServiceImplTest.java
Labels: ✨ feature, 🚑 fix

#28 [Domain] 집관련 도메인 모듈 서비스 구현
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/Monthly/domain/Monthly.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/Monthly/domain/MonthlyRepository.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/Monthly/service/MonthlyService.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/building/data/cond/FindBuildingOptionCond.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/building/domain/BuildingRepository.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/building/service/BuildingService.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/jeonse/domain/Jeonse.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/jeonse/domain/JeonseRepository.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/jeonse/service/JeonseService.java
  goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/building/building/domain/BuildingRepositoryTest.java
  goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/building/building/fixture/BuildingFixture.java
  goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/building/building/service/BuildingServiceTest.java
  goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/map/district/domain/DistrictRepositoryTest.java
  goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/map/district/fixture/DistrictFixture.java
  goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/map/district/service/DistrictServiceTest.java
  goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/map/legal/domain/LegalRepositoryTest.java
  goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/map/legal/fixture/LegalFixture.java
  goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/map/legal/service/LegalServiceTest.java
Labels: ✨ feature

#36 [Application & Domain] 역 데이터 DB에 저장
  goldmen-application/goldmen-batch/build.gradle
  goldmen-application/goldmen-batch/src/main/java/com/goldmen/home/BatchApplication.java
  goldmen-application/goldmen-batch/src/main/java/com/goldmen/home/BatchApplicationRunner.java
  goldmen-application/goldmen-batch/src/main/java/com/goldmen/home/station/service/StationService.java
  goldmen-client/kakao-client/src/main/java/com/goldmen/home/vo/Position.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/map/district/domain/DistrictRepository.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/map/district/service/DistrictService.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/map/legal/domain/LegalRepository.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/map/legal/service/LegalService.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/metro/line/service/LineLoadService.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/metro/line/service/LineServiceImpl.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/metro/station/domain/Station.java
  goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/map/district/fixture/DistrictFixture.java
  goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/map/legal/domain/LegalRepositoryTest.java
  goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/metro/line/service/LineServiceImplTest.java
  goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/metro/station/service/StationServiceImplTest.java
Labels: ✨ feature, 🐛 bug

#49 HouseService 버그 수정
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/building/service/HouseService.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/service/HouseService.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/metro/service/NearService.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/building/domain/BuildingEnum.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/metro/station/service/StationFindService.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/metro/station/service/StationReadService.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/metro/station/service/StationServiceImpl.java
Labels: 🐛 bug

#50 [ Application & Doamin ] 지도에 표시할 집 목록 가져오기
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/controller/HouseController.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/dto/response/GetHousePosition.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/dto/response/GetHousePositionResponse.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/service/HouseService.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/global/domain/Saleable.java
Labels: ✨ feature

#52 [Application & Domain] 매물 디테일 가져오기
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/controller/HouseController.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/dto/request/GetHouseRequest.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/dto/request/SaleableDetailRequest.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/dto/response/GetHouseResponse.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/dto/response/SaleableDetailResponse.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/service/HouseService.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/mapper/ApiMapper.java
  goldmen-application/goldmen-api/src/test/java/com/goldmen/home/house/service/HouseServiceTest.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/Monthly/domain/Monthly.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/Monthly/domain/MonthlyRepository.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/global/domain/PriceEnum.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/global/domain/Saleable.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/jeonse/domain/Jeonse.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/jeonse/domain/JeonseRepository.java
Labels: ✨ feature

#54 가까운 역 조회 기능 수정
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/metro/duration/domain/DurationRepository.java
Labels: ✨ feature

#55 [Application] 역 좌표 반환 추가
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/global/Mapper.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/metro/dto/NearMetroResponse.java
Labels: ✨ feature

#57 매물 가격, 평수 표시 방법 변경
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/dto/response/GetHouseResponse.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/dto/response/SaleableDetailResponse.java
Labels: ✨ feature

#62 fix: request Area수정
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/dto/request/Area.java
Labels: ✨ feature

#63 가까운 역 조회 기능 수정
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/global/Mapper.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/service/HouseService.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/metro/dto/NearMetroRequest.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/metro/dto/NearMetroResponse.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/metro/service/NearService.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/metro/duration/domain/DurationRepository.java
Labels: ✨ feature, 🐛 bug

#65 회원 정보 수정 기능 구현
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/controller/MemberController.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/dto/request/MemberUpdateRequest.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/service/MemberService.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/user/member/domain/Member.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/user/member/service/MemberModifyService.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/user/member/service/MemberServiceImpl.java
Labels: ✨ feature

#68 [Application & Domain] Spring Security, JWT등 기능을 추가
  .gitignore
  goldmen-application/goldmen-api/build.gradle
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/auth/annotation/Authenticated.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/auth/annotation/AuthenticatedArgumentResolver.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/auth/data/AuthMember.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/auth/data/dto/request/LoginRequest.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/auth/data/dto/request/ReissueRequest.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/auth/data/dto/response/TokenResponse.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/auth/service/AuthService.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/auth/service/CustomUserDetailService.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/auth/support/JwtAccessDeniedHandler.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/auth/support/JwtAuthenticationEntryPoint.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/auth/support/JwtFilter.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/auth/support/JwtSecurityConfig.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/auth/support/TokenProvider.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/global/CaffeineCacheType.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/global/CaffeineConfig.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/global/SecurityConfig.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/global/WebConfig.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/metro/duration/controller/NearController.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/metro/service/NearService.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/controller/MemberController.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/mapper/MemberMapper.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/service/MemberService.java
  goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/message/MemberMessage.java
  goldmen-application/goldmen-api/src/test/java/com/goldmen/home/metro/service/NearServiceTest.java
  goldmen-application/goldmen-api/src/test/java/com/goldmen/home/user/member/service/MemberServiceTest.java
  goldmen-domain/jpa-domain/build.gradle
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/user/member/domain/Member.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/user/member/service/MemberLoadService.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/user/member/service/MemberModifyService.java
  goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/user/member/service/MemberServiceImpl.java
  goldmen-domain/redis-domain/build.gradle
  goldmen-domain/redis-domain/src/main/java/com/goldmen/home/.gitkeep
  goldmen-domain/redis-domain/src/main/java/com/goldmen/home/auth/domain/Token.java
  goldmen-domain/redis-domain/src/main/java/com/goldmen/home/auth/domain/TokenRepository.java
  goldmen-domain/redis-domain/src/main/java/com/goldmen/home/auth/service/TokenLoadService.java
  goldmen-domain/redis-domain/src/main/java/com/goldmen/home/auth/service/TokenModifyService.java
  goldmen-domain/redis-domain/src/main/java/com/goldmen/home/auth/service/TokenService.java
Labels: ✨ feature
